--------------------------------------------------------
--  File created - Tuesday-April-29-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "AHMED"."CLIENTS" 
   (	"CLIENT_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"SECTOR" VARCHAR2(100 BYTE), 
	"CONTACT_INFO" VARCHAR2(15 BYTE), 
	"CONSULTATION_DATE" TIMESTAMP (6), 
	"CONSULTANT" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"CONSULTANT_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "AHMED"."EMPLOYEE" 
   (	"ID" NUMBER(*,0), 
	"CIN" VARCHAR2(30 BYTE), 
	"LAST_NAME" VARCHAR2(30 BYTE), 
	"FIRST_NAME" VARCHAR2(30 BYTE), 
	"DATE_BIRTH" DATE, 
	"PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"SALARY" NUMBER(*,0), 
	"DATE_HIRING" DATE, 
	"SPECIALITY" VARCHAR2(40 BYTE), 
	"IMAGE" BLOB, 
	"ROLE" VARCHAR2(40 BYTE), 
	"RFID_UID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FORMATIONS
--------------------------------------------------------

  CREATE TABLE "AHMED"."FORMATIONS" 
   (	"IDFORM" NUMBER(*,0), 
	"FORMATION" VARCHAR2(30 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"TRAINER" VARCHAR2(20 BYTE), 
	"DATEF" DATE, 
	"TIME" NUMBER(*,0), 
	"PRIX" NUMBER(*,0), 
	"EPLOYEE_ID" NUMBER(*,0), 
	"CLIENT_ID" NUMBER(*,0), 
	"RESSOURCE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEETING
--------------------------------------------------------

  CREATE TABLE "AHMED"."MEETING" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(41 BYTE), 
	"ORGANISER" VARCHAR2(40 BYTE), 
	"PARTICIPANT" VARCHAR2(40 BYTE), 
	"AGENDA" VARCHAR2(40 BYTE), 
	"DURATION" NUMBER, 
	"EMPLOYEE_ID" NUMBER(*,0), 
	"CLIENT_ID" NUMBER(*,0), 
	"RESSOURCE_ID" NUMBER(*,0), 
	"DATEM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESOURCES
--------------------------------------------------------

  CREATE TABLE "AHMED"."RESOURCES" 
   (	"RESOURCE_ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"BRAND" VARCHAR2(50 BYTE), 
	"QUANTITY" NUMBER, 
	"PURCHASE_DATE" DATE, 
	"IMAGE" BLOB, 
	"EMPLOYEE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into AHMED.CLIENTS
SET DEFINE OFF;
Insert into AHMED.CLIENTS (CLIENT_ID,NAME,SECTOR,CONTACT_INFO,CONSULTATION_DATE,CONSULTANT,EMAIL,CONSULTANT_ID) values (3,'azer','finance','53413451',to_timestamp('01-JAN-25 08.34.39.145000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'AHMED','azer@gmail.com',41);
Insert into AHMED.CLIENTS (CLIENT_ID,NAME,SECTOR,CONTACT_INFO,CONSULTATION_DATE,CONSULTANT,EMAIL,CONSULTANT_ID) values (90,'ahmedssss','dqsdqdqsd','123455',to_timestamp('26-MAY-25 11.31.26.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,'shaco54lol@gmail.com',41);
Insert into AHMED.CLIENTS (CLIENT_ID,NAME,SECTOR,CONTACT_INFO,CONSULTATION_DATE,CONSULTANT,EMAIL,CONSULTANT_ID) values (91,'qsdfghjuk','fghjk','12345678',to_timestamp('26-MAY-25 02.36.54.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,'shaco54lol@gmail.com',41);
Insert into AHMED.CLIENTS (CLIENT_ID,NAME,SECTOR,CONTACT_INFO,CONSULTATION_DATE,CONSULTANT,EMAIL,CONSULTANT_ID) values (1,'abidi','flirting','33705166',to_timestamp('25-APR-25 08.35.45.403000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'AHMED','abidi@gmail.com',41);
REM INSERTING into AHMED.EMPLOYEE
SET DEFINE OFF;
Insert into AHMED.EMPLOYEE (ID,CIN,LAST_NAME,FIRST_NAME,DATE_BIRTH,PHONE,EMAIL,GENDER,SALARY,DATE_HIRING,SPECIALITY,ROLE,RFID_UID) values (41,'14530334','HAJJI','AHMED',to_date('01-JAN-00','DD-MON-RR'),'29167398','ahmed@gmail.com','Homme',20000,to_date('01-JAN-25','DD-MON-RR'),'Informatique','Admin','A3E82928');
Insert into AHMED.EMPLOYEE (ID,CIN,LAST_NAME,FIRST_NAME,DATE_BIRTH,PHONE,EMAIL,GENDER,SALARY,DATE_HIRING,SPECIALITY,ROLE,RFID_UID) values (1,'14530338','loukil','khalil',to_date('01-JAN-02','DD-MON-RR'),'94184831','khalil@gmail.com','Homme',1000,to_date('01-JAN-25','DD-MON-RR'),'Informatique','Employee','5185B17B');
Insert into AHMED.EMPLOYEE (ID,CIN,LAST_NAME,FIRST_NAME,DATE_BIRTH,PHONE,EMAIL,GENDER,SALARY,DATE_HIRING,SPECIALITY,ROLE,RFID_UID) values (46,'13547763','ben moussa','mohamed',to_date('01-JUL-04','DD-MON-RR'),'98474731','mohamed@gmail.com','Homme',1000,to_date('12-MAR-25','DD-MON-RR'),'Informatique','Admin',null);
Insert into AHMED.EMPLOYEE (ID,CIN,LAST_NAME,FIRST_NAME,DATE_BIRTH,PHONE,EMAIL,GENDER,SALARY,DATE_HIRING,SPECIALITY,ROLE,RFID_UID) values (48,'14536341','RAREARA','GERARA',to_date('01-JAN-00','DD-MON-RR'),'23814313','GARAE@gmail.com','Homme',2133,to_date('01-JAN-25','DD-MON-RR'),'Informatique','Admin',null);
Insert into AHMED.EMPLOYEE (ID,CIN,LAST_NAME,FIRST_NAME,DATE_BIRTH,PHONE,EMAIL,GENDER,SALARY,DATE_HIRING,SPECIALITY,ROLE,RFID_UID) values (42,'14539414','belhaj','omar',to_date('12-FEB-03','DD-MON-RR'),'53645149','omar@gmail.com','Homme',1200,to_date('10-MAR-25','DD-MON-RR'),'Informatique','Employee',null);
Insert into AHMED.EMPLOYEE (ID,CIN,LAST_NAME,FIRST_NAME,DATE_BIRTH,PHONE,EMAIL,GENDER,SALARY,DATE_HIRING,SPECIALITY,ROLE,RFID_UID) values (47,'16732873','frej','aymen',to_date('01-JUL-02','DD-MON-RR'),'98372747','aymen@gmail.com','Homme',1900,to_date('12-MAR-25','DD-MON-RR'),'Communication','Employee','50FA2285');
REM INSERTING into AHMED.FORMATIONS
SET DEFINE OFF;
Insert into AHMED.FORMATIONS (IDFORM,FORMATION,DESCRIPTION,TRAINER,DATEF,TIME,PRIX,EPLOYEE_ID,CLIENT_ID,RESSOURCE_ID) values (21,'electro','besh ta9ra lili itmout','omar',to_date('19-JAN-00','DD-MON-RR'),22,0,null,null,null);
Insert into AHMED.FORMATIONS (IDFORM,FORMATION,DESCRIPTION,TRAINER,DATEF,TIME,PRIX,EPLOYEE_ID,CLIENT_ID,RESSOURCE_ID) values (22,'ahmedsqssssss','bara','mohamed',to_date('30-APR-26','DD-MON-RR'),11,6,null,null,null);
REM INSERTING into AHMED.MEETING
SET DEFINE OFF;
Insert into AHMED.MEETING (ID,TITLE,ORGANISER,PARTICIPANT,AGENDA,DURATION,EMPLOYEE_ID,CLIENT_ID,RESSOURCE_ID,DATEM) values (20,'gdfgfs','gsfd','sfg','car advice',14,null,null,null,null);
Insert into AHMED.MEETING (ID,TITLE,ORGANISER,PARTICIPANT,AGENDA,DURATION,EMPLOYEE_ID,CLIENT_ID,RESSOURCE_ID,DATEM) values (11,'trdhy','eytry','trey','life advice',14,null,null,null,null);
Insert into AHMED.MEETING (ID,TITLE,ORGANISER,PARTICIPANT,AGENDA,DURATION,EMPLOYEE_ID,CLIENT_ID,RESSOURCE_ID,DATEM) values (21,'ahmed','juju','aszqsd','car advice',14,null,null,null,null);
Insert into AHMED.MEETING (ID,TITLE,ORGANISER,PARTICIPANT,AGENDA,DURATION,EMPLOYEE_ID,CLIENT_ID,RESSOURCE_ID,DATEM) values (22,'sssssss','sssssssssssss','ssssssssss','car advice',14,null,null,null,null);
Insert into AHMED.MEETING (ID,TITLE,ORGANISER,PARTICIPANT,AGENDA,DURATION,EMPLOYEE_ID,CLIENT_ID,RESSOURCE_ID,DATEM) values (17,'htrh','rtytr','rtyrt','life advice',14,null,null,null,null);
Insert into AHMED.MEETING (ID,TITLE,ORGANISER,PARTICIPANT,AGENDA,DURATION,EMPLOYEE_ID,CLIENT_ID,RESSOURCE_ID,DATEM) values (16,'fdsfds','fdsfez','sdfez','car advice',14,null,null,null,null);
Insert into AHMED.MEETING (ID,TITLE,ORGANISER,PARTICIPANT,AGENDA,DURATION,EMPLOYEE_ID,CLIENT_ID,RESSOURCE_ID,DATEM) values (19,'hbjh','nik','vgh','life advice',14,null,null,null,null);
REM INSERTING into AHMED.RESOURCES
SET DEFINE OFF;
Insert into AHMED.RESOURCES (RESOURCE_ID,NAME,TYPE,BRAND,QUANTITY,PURCHASE_DATE,EMPLOYEE_ID) values (9,'fdgdfg','Cleaning Supplies','fjghgfj',555,to_date('01-JAN-00','DD-MON-RR'),null);
Insert into AHMED.RESOURCES (RESOURCE_ID,NAME,TYPE,BRAND,QUANTITY,PURCHASE_DATE,EMPLOYEE_ID) values (10,null,'Electronics ',null,0,to_date('01-JAN-00','DD-MON-RR'),null);
Insert into AHMED.RESOURCES (RESOURCE_ID,NAME,TYPE,BRAND,QUANTITY,PURCHASE_DATE,EMPLOYEE_ID) values (11,'dfg','Furniture','dfg',55,to_date('01-JAN-00','DD-MON-RR'),null);
Insert into AHMED.RESOURCES (RESOURCE_ID,NAME,TYPE,BRAND,QUANTITY,PURCHASE_DATE,EMPLOYEE_ID) values (7,'ahmed','Stationery','dfsdf',55,to_date('01-JAN-00','DD-MON-RR'),null);
Insert into AHMED.RESOURCES (RESOURCE_ID,NAME,TYPE,BRAND,QUANTITY,PURCHASE_DATE,EMPLOYEE_ID) values (8,'ddsfsdf','Kitchen Supplies ','dsfgdfg',7777,to_date('01-JAN-00','DD-MON-RR'),null);
--------------------------------------------------------
--  DDL for Index CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."CLIENTS_PK" ON "AHMED"."CLIENTS" ("CLIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."EMPLOYEE_PK" ON "AHMED"."EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FORMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."FORMATION_PK" ON "AHMED"."FORMATIONS" ("IDFORM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."TABLE1_PK" ON "AHMED"."MEETING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESOURCES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."RESOURCES_PK" ON "AHMED"."RESOURCES" ("RESOURCE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CLIENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AHMED"."CLIENTS_TRG" 
BEFORE INSERT ON CLIENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "AHMED"."CLIENTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYEE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AHMED"."EMPLOYEE_TRG1" 
BEFORE INSERT ON EMPLOYEE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT EMPLOYEE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "AHMED"."EMPLOYEE_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYEE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AHMED"."EMPLOYEE_TRG" 
BEFORE INSERT ON EMPLOYEE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "AHMED"."EMPLOYEE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FORMATION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AHMED"."FORMATION_TRG" 
BEFORE INSERT ON FORMATIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "AHMED"."FORMATION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FORMATIONS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AHMED"."FORMATIONS_TRG" 
BEFORE INSERT ON FORMATIONS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "AHMED"."FORMATIONS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MEETING_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AHMED"."MEETING_TRG" 
BEFORE INSERT ON MEETING 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "AHMED"."MEETING_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MEETING_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AHMED"."MEETING_TRG1" 
BEFORE INSERT ON MEETING 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AHMED"."MEETING_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TABLE1_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AHMED"."TABLE1_TRG" 
BEFORE INSERT ON MEETING 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "AHMED"."TABLE1_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RESOURCE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AHMED"."RESOURCE_TRIGGER" 
BEFORE INSERT ON resources
FOR EACH ROW
BEGIN
  IF :NEW.RESOURCE_ID IS NULL THEN
    SELECT resource_seq.NEXTVAL INTO :NEW.RESOURCE_ID FROM DUAL;
  END IF;
END;




/
ALTER TRIGGER "AHMED"."RESOURCE_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "AHMED"."CLIENTS" MODIFY ("CONSULTANT_ID" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."CLIENTS" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."CLIENTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."CLIENTS" ADD CONSTRAINT "CLIENTS_PK" PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "AHMED"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMED"."EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."EMPLOYEE" MODIFY ("SPECIALITY" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."EMPLOYEE" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."EMPLOYEE" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."EMPLOYEE" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."EMPLOYEE" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."EMPLOYEE" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."EMPLOYEE" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FORMATIONS
--------------------------------------------------------

  ALTER TABLE "AHMED"."FORMATIONS" MODIFY ("IDFORM" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."FORMATIONS" ADD CONSTRAINT "FORMATION_PK" PRIMARY KEY ("IDFORM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMED"."FORMATIONS" MODIFY ("FORMATION" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."FORMATIONS" MODIFY ("TRAINER" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."FORMATIONS" MODIFY ("DATEF" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."FORMATIONS" MODIFY ("TIME" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."FORMATIONS" MODIFY ("PRIX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEETING
--------------------------------------------------------

  ALTER TABLE "AHMED"."MEETING" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."MEETING" MODIFY ("ORGANISER" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."MEETING" MODIFY ("PARTICIPANT" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."MEETING" MODIFY ("AGENDA" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."MEETING" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESOURCES
--------------------------------------------------------

  ALTER TABLE "AHMED"."RESOURCES" MODIFY ("RESOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."RESOURCES" ADD CONSTRAINT "RESOURCES_PK" PRIMARY KEY ("RESOURCE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "AHMED"."CLIENTS" ADD CONSTRAINT "CLIENTS_FK1" FOREIGN KEY ("CONSULTANT_ID")
	  REFERENCES "AHMED"."EMPLOYEE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FORMATIONS
--------------------------------------------------------

  ALTER TABLE "AHMED"."FORMATIONS" ADD CONSTRAINT "CLIENT_FK1" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "AHMED"."CLIENTS" ("CLIENT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AHMED"."FORMATIONS" ADD CONSTRAINT "EMPLOYEE_FK2" FOREIGN KEY ("EPLOYEE_ID")
	  REFERENCES "AHMED"."EMPLOYEE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AHMED"."FORMATIONS" ADD CONSTRAINT "RESSOURCE_FK2" FOREIGN KEY ("RESSOURCE_ID")
	  REFERENCES "AHMED"."RESOURCES" ("RESOURCE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEETING
--------------------------------------------------------

  ALTER TABLE "AHMED"."MEETING" ADD CONSTRAINT "CLIENT_FK" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "AHMED"."CLIENTS" ("CLIENT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AHMED"."MEETING" ADD CONSTRAINT "EMPLOYEE_FK" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "AHMED"."EMPLOYEE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AHMED"."MEETING" ADD CONSTRAINT "RESSOURCE_FK" FOREIGN KEY ("RESSOURCE_ID")
	  REFERENCES "AHMED"."RESOURCES" ("RESOURCE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESOURCES
--------------------------------------------------------

  ALTER TABLE "AHMED"."RESOURCES" ADD CONSTRAINT "EMPLOYEE_FK1" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "AHMED"."EMPLOYEE" ("ID") ON DELETE CASCADE ENABLE;
